"use client";
import { useMediaUpload } from "@/components/editor/mediaUpload";

/**
 * THE BUNDLED SAMPLE — ART-DIRECTION §13's empty state, and §1/§11's asset ledger.
 *
 * §13 asks for three example prompts on the first screen, and adds the sentence that makes them
 * worth having: "each one loads the bundled sample take and runs." The jury's note it is adopted
 * from is the reason — the old empty state "offered an input that could not act and three links that
 * could not run: a dead field and three dead links as the product's first screen."
 *
 * AND THE TAKE DOES NOT EXIST YET. §11's asset ledger is exhaustive and it is checked: the only
 * raster in the repository is one Playwright snapshot and the only vector is `public/kite.svg`.
 * `public/take/` holds no media, `lib/landing/fixture-source.ts` still carries its "THERE IS NO
 * FOOTAGE" header, and §1 defines the one 48-second take that retires all of it. So this module says
 * so out loud instead of shipping a button that 404s, and the empty state degrades to the honest
 * second-best: the sentence is HELD and runs by itself the moment there is footage to run it on.
 *
 * TO TURN IT ON, when §1's take lands: commit `public/take/take.mp4` and set `SAMPLE_TAKE` below.
 * Nothing else changes — the examples already call `loadSampleTake()` and already re-send their held
 * sentence when the timeline appears.
 */

export interface SampleTake {
  /** Path under `public/`. */
  readonly url: string;
  /** The filename the asset row is created with. */
  readonly filename: string;
  readonly mimeType: string;
}

/**
 * The take that ships with the repository, generated by `scripts/make-sample-take.mjs`.
 *
 * It is deliberately synthetic: eight labelled, hard-cut scenes over a steady 120 BPM pulse. Real
 * footage would mean shipping someone's likeness and someone's licence, and shipping nothing meant
 * every newcomer's first experience of HITE was an empty file picker. Synthetic also makes the edit
 * legible — you can see which of the eight the model kept and where it cut.
 *
 * Every caller still branches on `sampleTakeAvailable()`, so removing the file degrades to the
 * previous behaviour rather than breaking the empty state.
 */
export const SAMPLE_TAKE: SampleTake | null = {
  url: "/take/take.mp4",
  filename: "take.mp4",
  mimeType: "video/mp4",
};

export function sampleTakeAvailable(): boolean {
  return SAMPLE_TAKE !== null;
}

export type SampleLoad =
  | { readonly ok: true }
  /** The take is not shipped in this build. The caller must not claim it is. */
  | { readonly ok: false; readonly reason: "unavailable" }
  /** It is shipped and the fetch failed, in the browser's own words. */
  | { readonly ok: false; readonly reason: "failed"; readonly detail: string };

/**
 * Put the bundled take on the workbench, through the ONE upload path.
 *
 * Deliberately `useMediaUpload.uploadFiles` rather than a shortcut: the sample has to become a real
 * asset row with a real probed duration, or `/api/plan` refuses the project with "no usable asset"
 * and the example prompt that loaded it fails on the next breath. Reusing the pipeline also means
 * the sample reports its progress and its failures exactly like a dropped file.
 */
export async function loadSampleTake(projectId: string): Promise<SampleLoad> {
  const take = SAMPLE_TAKE;
  if (!take) return { ok: false, reason: "unavailable" };
  try {
    const res = await fetch(take.url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const blob = await res.blob();
    const file = new File([blob], take.filename, { type: take.mimeType });
    await useMediaUpload.getState().uploadFiles(projectId, [file]);
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: "failed", detail: e instanceof Error ? e.message : String(e) };
  }
}
